# AUTOGENERATED! DO NOT EDIT! File to edit: ../Notebooks/00_create_csv/01_loading_pipal.ipynb.

# %% auto 0
__all__ = []

# %% ../Notebooks/00_create_csv/01_loading_pipal.ipynb 2
import re

import pandas as pd
from pathlib import Path
from natsort import natsorted
from fastcore.foundation import L
