# AUTOGENERATED! DO NOT EDIT! File to edit: ../Notebooks/00_create_csv/03_loading_tid2013.ipynb.

# %% auto 0
__all__ = []

# %% ../Notebooks/00_create_csv/03_loading_tid2013.ipynb 2
import re

import pandas as pd
from pathlib import Path
from natsort import natsorted
from fastcore.foundation import L

# %% ../Notebooks/00_create_csv/03_loading_tid2013.ipynb 10
def get_ref_name(dist_name):
    file, extension = re.search(r"(.+)_\d+_\d+\.(.+)", dist_name).groups()
    return ".".join((file, extension)).upper()
