# AUTOGENERATED! DO NOT EDIT! File to edit: ../Notebooks/00_create_csv/04_loading_bapps.ipynb.

# %% auto 0
__all__ = []

# %% ../Notebooks/00_create_csv/04_loading_bapps.ipynb 2
import re

import pandas as pd
# from pathlib import Path
# from natsort import natsorted
from fastcore.basics import Path
from fastcore.foundation import L
