# AUTOGENERATED! DO NOT EDIT! File to edit: ../Notebooks/00_create_csv/02_loading_tid2008.ipynb.

# %% auto 0
__all__ = []

# %% ../Notebooks/00_create_csv/02_loading_tid2008.ipynb 2
import re

import pandas as pd
from pathlib import Path
from natsort import natsorted
from fastcore.foundation import L

# %% ../Notebooks/00_create_csv/02_loading_tid2008.ipynb 8
def fix_dist_name(name):
    file, extension = name.split(".")
    file, extension = file.upper(), extension.lower()
    return ".".join([file, extension])

# %% ../Notebooks/00_create_csv/02_loading_tid2008.ipynb 11
def get_ref_name(dist_name):
    file, extension = re.search(r"(.+)_\d+_\d+\.(.+)", dist_name).groups()
    return ".".join((file, extension)).upper()
